services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - internal

  api:
    build: ../backend
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - PORT=5000
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=root_default"
      - "traefik.http.routers.myrealtor-api.rule=Host(`apimyrealtor.nodesafe.cloud`)"
      - "traefik.http.routers.myrealtor-api.entrypoints=websecure"
      - "traefik.http.routers.myrealtor-api.tls=true"
      - "traefik.http.routers.myrealtor-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.myrealtor-api.loadbalancer.server.port=5000"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - root_default
      - internal

  frontend:
    build:
      context: ../frontend
      args:
        - VITE_API_URL=https://apimyrealtor.nodesafe.cloud/api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myrealtor-web.rule=Host(`myrealtor.nodesafe.cloud`)"
      - "traefik.http.routers.myrealtor-web.entrypoints=websecure"
      - "traefik.http.routers.myrealtor-web.tls=true"
      - "traefik.http.routers.myrealtor-web.tls.certresolver=mytlschallenge"
      - "traefik.http.services.myrealtor-web.loadbalancer.server.port=80"
    networks:
      - root_default

volumes:
  mongo_data:
  uploads_data:

networks:
  internal:
    driver: bridge

  root_default:
    external: true
